### ISSUE TITLE
'play'-command

### ISSUE THREAD

**Issue by marcothms** [CramMK/aquabot#1]

**Comment by marcothms** [comment]
queue feature

**Comment by CramMK** [comment]
removing played songs
(check if a youtube-* exists, if yes -> delete)

**Comment by CramMK** [comment]
join automatically when using "play"

**Comment by CramMK** [comment]
https://stackoverflow.com/questions/53605422/discord-py-music-bot-how-to-combine-a-play-and-queue-command

**Comment by CramMK** [comment]
https://gist.github.com/vbe0201/ade9b80f2d3b64643d854938d40a0a2d
